lib/unix/sys/filesystem.rb

I've had problems using sys-filesystem's Filesystem.mount_point(<dir>) when the directory is under a USB mounted file system when we are using gnome gvfs auto loader and there are multiple users on the system. It seems as if the users will grab hold of the directory and not even the root user can do a File.stat on that directory. 
So I've put a check in for any gvfs to ignore it.

check for gvfs before doing a stat

---

lib/unix/sys/filesystem.rb

Per: https://github.com/djberg96/sys-filesystem/issues/14.
I specifically targeted FreeBSD10 only in this change as I do not have access to older versions and don't want to chance breaking them.

Fix for FreeBSD 10 block_size

---

lib/sys/unix/sys/filesystem.rb

In chroots only /proc/mounts is present. Fixes: #22

use /proc/mounts as a fallback

---

lib/sys/unix/sys/filesystem/structs.rb

In FreeBSD 12.0 struct statfs, size of f_mntfromname and f_mnttonname changed from 88 to 1024.

FreeBSD 12.0 statfs MNAMELEN from 88 => 1024.

---

lib/sys/unix/sys/filesystem.rb

For space calculations we should use fragment_size instead of block_size.
A WIP for now as I check other platforms to verify.

Use fragment_size instead of block_size

---

lib/sys/unix/sys/filesystem.rb
test/test_sys_filesystem_unix.rb

Currently `bytes_free` on Unix is calculated based on `blocks_available`, not on `blocks_free`. It looks inconsistent. I think, `bytes_free` should be calculated based on `blocks_free`. If someone wants to know available bytes - maybe a new method `bytes_available` should be introduced.
On Windows free space calculation is done differently, but consistently: `blocks_free` is calculated based on `block_size`.

Fixed calculation of bytes_free on Unix.

---

examples/example_stat.rb
lib/sys/unix/sys/filesystem.rb
lib/sys/windows/sys/filesystem.rb
test/test_sys_filesystem_unix.rb
test/test_sys_filesystem_windows.rb

This pull request adds Stat.bytes_available method and a couple of other small improvements.
Note that I could not test the Windows changes, because I don't have a setup for it. I added Windows-specific code for `bytes_available` similarly to how the code for `bytes_free` is written.

Stat.bytes_available method

---

CHANGES
lib/sys/filesystem.rb
lib/sys/unix/sys/filesystem.rb
lib/sys/unix/sys/filesystem/constants.rb
lib/sys/unix/sys/filesystem/functions.rb
lib/sys/windows/sys/filesystem.rb
lib/sys/windows/sys/filesystem/functions.rb
sys-filesystem.gemspec
test/test_sys_filesystem_unix.rb
test/test_sys_filesystem_windows.rb

This adds the `mount` and `umount` singleton methods to the base `Sys::Filesystem` class. On Unix systems, this is a thin wrapper around the `mount` and `umount` functions (or `unmount` on Macs).
While Windows isn't a precise analogue, I've made it as close as I can, wrapping the `SetVolumeMountPoint` method. Internally I use the `GetVolumeNameForVolumeMountPoint` so that users don't have to calculate the underlying volume name manually.
Otherwise, the only change was to switch `@@opt_names` to `OPT_NAMES`.

Add a mount singleton method

---

CHANGES
lib/sys/filesystem.rb
lib/sys/unix/sys/filesystem/functions.rb
lib/sys/unix/sys/filesystem/structs.rb
sys-filesystem.gemspec
test/test_sys_filesystem_unix.rb
test/test_sys_filesystem_windows.rb

Addresses https://github.com/djberg96/sys-filesystem/issues/35, plus some other cleanup.
Specifically:
* Fixes the Statvfs and Statfs wrapper structs for Linux.
* Some updates and fixes for BSD.
* Updated the unix tests to use the nicer description text (the windows tests were already updated).
* Added mkmf-lite as a development dependency.
* Added specs to ensure that the FFI wrapper struct is the same size as the underlying C struct.

Fix Statvfs struct size, test cleanup

---

lib/sys/filesystem.rb
lib/sys/unix/sys/filesystem/functions.rb
test/test_sys_filesystem_unix.rb

Looks like back in October last year, we updated the statvfs struct for Linux to 64 bit, but did not update the underlying method:
https://github.com/djberg96/sys-filesystem/commit/f3c62ea84cd2fa824b6d27391113ccb226f743d7#diff-c7438eda74c2cc86e244729f5cd0f298
The result is that 32bit systems can end up with bad info.
Addresses:
https://github.com/djberg96/sys-filesystem/issues/39

Use statvfs64 on linux

---

CHANGES.rdoc
LICENSE
MANIFEST.rdoc
lib/sys/filesystem.rb
sys-filesystem.gemspec
test/test_sys_filesystem_unix.rb
test/test_sys_filesystem_windows.rb

As per the redistribution clause of the Apache-2.0 license, I'm supposed to be including a copy of the license with the distribution if I use the Apache-2.0 license.
This PR adds it and updates the various version related bits.

Add LICENSE file

---

lib/sys/unix/sys/filesystem/structs.rb

On Centos 6 and Debian 8, both i686 architectures Sys::FileSystem.stat returns invalid values:
```
irb(main):003:0> Sys::Filesystem::VERSION
=> "1.3.2"
irb(main):004:0> Sys::Filesystem.stat('/')
=> #<Sys::Filesystem::Stat:0x09295de8 @path="/", 
@block_size=4096, 
@fragment_size=4096, 
@blocks=18564931717193332, 
@blocks_free=5211753839214876, 
@blocks_available=4845603579311885, 
@files=2694623991, 
@files_free=1095216664576, 
@files_available=0, 
@filesystem_id=0, 
@flags=0, 
@name_max=0, 
@base_type=nil>
```
This happens because the Statvfs structure for unix systems has uint64_t value types instead of uint.
After the fix is applied, the stat method returns correct values:
```
irb(main):002:0> Sys::Filesystem.stat('/')
=> #<Sys::Filesystem::Stat:0x0a2da348 @path="/", 
@block_size=4096, …
```

Statvfs layout for i686 unix architectures

---

.gitignore
CHANGES.md
README.md
lib/sys/filesystem.rb
lib/sys/unix/sys/filesystem/functions.rb
spec/sys_filesystem_unix_spec.rb
spec/sys_filesystem_windows_spec.rb
sys-filesystem.gemspec

As of Big Sur, the `getmntinfo64` function is no longer exported, instead it simply uses a 64-bit version of `getmntinfo`. So this PR handles both situations, falling back to `getmntinfo` if `getmntinfo64` isn't found.
I also fixed a minor issue with the changelog URI, and added a .gitignore file.

Update for Big Sur

---

Rakefile
examples/example_mount.rb
lib/sys/unix/sys/filesystem.rb
lib/sys/unix/sys/filesystem/constants.rb
lib/sys/windows/sys/filesystem.rb

Fixes some unused variables, as well as fixing some private access modifiers and/or removing useless ones.

Rubocop linter fixes

---

Gemfile
spec/sys_filesystem_unix_spec.rb
sys-filesystem.gemspec

This fixes a few issues that were revealed by github actions, and changes some things around. Namely:
* Just use the gemspec for the Gemfile, it's easier and I had accidentally left fakefs in there.
* Only require mkmf-lite on non-Windows platforms.
* Fixes an issue where rspec was evaluating a require statement in the Unix spec on Windows that would fail.

Fix require and update specs in unix example group, update Gemfile

---

lib/sys/unix/sys/filesystem/functions.rb
lib/sys/unix/sys/filesystem/structs.rb

Handle 32-bit Linux properly. This means not using 64-bit functions, and using the appropriate struct.
Tested locally on Ubuntu 16, Fedora 34 and RHEL 8.
Replacement for https://github.com/djberg96/sys-filesystem/pull/56

Handle 32-bit Linux properly

---

lib/sys/unix/sys/filesystem/structs.rb

On 32-bit linux, ruby's configure script detects that FILE_OFFSET_BITS=64 is required to access the 64-bit filesystem interface and adds the following to rbconfig.rb:
CONFIG["DEFS"] = "-D_FILE_OFFSET_BITS=64"
The sys-filesystem gem was modified in 68d6cdb978d4d25b25d9eafa5e1e5b5642e88578 to detect that case and call the 64-bit version of `statvfs`. The `Statfs` struct was also modified, but the similarly named `Statvfs` struct wasn't. So the following segfaulted on 32-bit linux:
$ ruby -rsys-filesystem -e "Sys::Filesystem.stat('/')"
*** glibc detected *** /opt/puppetlabs/puppet/bin/ruby: double free or corruption (!prev): 0x094b1c58 ***

Fix segfault when calling statvfs on 32-bit linux

---

CHANGES.md
lib/sys/filesystem.rb
lib/sys/unix/sys/filesystem/functions.rb
spec/sys_filesystem_shared.rb
spec/sys_filesystem_unix_spec.rb
sys-filesystem.gemspec

Apparently not all 64-bit Linux distros have a statvfs64 function or alias.
Addresses https://github.com/djberg96/sys-filesystem/issues/66

Handle possibility that statvfs64 doesn't exist on 64-bit platforms

---

CHANGES.md
lib/sys/filesystem.rb
lib/sys/unix/sys/filesystem.rb
lib/sys/unix/sys/filesystem/constants.rb
lib/sys/unix/sys/filesystem/functions.rb
lib/sys/unix/sys/filesystem/structs.rb
spec/spec_helper.rb
spec/sys_filesystem_shared.rb
spec/sys_filesystem_unix_spec.rb
sys-filesystem.gemspec

The primary purpose of this PR is to add DragonFlyBSD support. Note that it was tested with the HAMMER2 filesystem, I'm not sure if it works with a standard UFS filesystem, but it appears to be the default so I went with it.
I also updated the `umount` method, which now assumes that the `umount2` function is defined on Linux systems. This simplified the implementation of the corresponding Ruby method.
Last, I decided to finally remove Solaris support. It's dead.

Add Dragonflybsd support, refactor umount

---

lib/sys/unix/sys/filesystem/structs.rb

It's been added in both glibc and musl. Glibc has been zeroing out the spare ints since the dawn of time and musl since at least 1.0.0, so it's safe to simply check if these values are nonzero.
https://github.com/bminor/glibc/commit/92861d93cdad13834f4d8f39504b550a80ad8200
https://github.com/bminor/musl/commit/7291c6c66a8d033bb487e6d8c8b003c8a7b6a550

Add f_type field to struct statvfs

---

lib/sys/unix/sys/filesystem/structs.rb

Effectively does what musl does, which also works for glibc.
Closes #71

Add padding on 32 bit statvfs with 64 bit offsets

---

sys-filesystem.gemspec

Make mkmf-lite a runtime dependency
Since 305b6b77931a4e3b328559b5367e2c617c0d0f83 the gem is used at runtime too.
FIXES: #74

Make mkmf-lite a runtime dependency

---

lib/sys/unix/sys/filesystem/structs.rb

Reverts djberg96/sys-filesystem#73. This is causing too many issues. I'll have to rethink this, or simply declare that I'm not going to support mixing and matching 32v64.

Revert "Add padding on 32 bit statvfs with 64 bit offsets"

---

CHANGES.md
README.md
lib/sys/filesystem.rb
spec/sys_filesystem_shared.rb
sys-filesystem.gemspec

Explains the changes for 1.5.3, and moves mkmf-lite back to a dev dependency.

Update for 1.5.3

---

sys-filesystem.gemspec

I noticed that the project already has a FUNDING.yml. This PR adds the `funding_uri` to your gemspec to help increase visibility using the `bundle fund` command in Bundler.

Add funding_uri to gemspec
